=== thelia/thelia/core/lib/Thelia/Module/schema/module/module-2_2.xsd
<?xml version="1.0" encoding='UTF-8'?>
<xs:schema
        xmlns="http://thelia.net/schema/dic/module"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://thelia.net/schema/dic/module"
        attributeFormDefault="unqualified"
        elementFormDefault="qualified"
        >

    <xs:element name="module">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" minOccurs="1" name="fullnamespace">
                    <xs:annotation>
                        <xs:documentation>The full namespace for the main class module (for example MyModule\MyModule)</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="descriptive" minOccurs="1" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>Complete description, each description must be identify by ISO CODE 639</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="title" minOccurs="1" maxOccurs="1"/>
                            <xs:element type="xs:string" name="subtitle" minOccurs="0" maxOccurs="1"/>
                            <xs:element type="xs:string" name="description" minOccurs="0" maxOccurs="1"/>
                            <xs:element type="xs:string" name="postscriptum" minOccurs="0" maxOccurs="1"/>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="locale"/>
                    </xs:complexType>
                </xs:element>
                <xs:element type="xs:string" minOccurs="0" maxOccurs="1" name="logo">
                    <xs:annotation>
                        <xs:documentation>The path to the logo of the module (for example myModule.png). The recommended size is 128x128.</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element type="xs:string" minOccurs="0" maxOccurs="1" name="images-folder">
                    <xs:annotation>
                        <xs:documentation>The folder that contains the images to deploy.</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="languages">
                    <xs:annotation>
                        <xs:documentation>Module languages supported : fr_FR, en_US, ...</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="language" minOccurs="1" maxOccurs="unbounded">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-z]{2}_[A-Z]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element type="xs:string" name="version">
                    <xs:annotation>
                        <xs:documentation>Module version</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="authors" maxOccurs="1" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>Module authors</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="author" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="name" minOccurs="1" maxOccurs="1"/>
                                        <xs:element type="xs:string" name="company" minOccurs="0" maxOccurs="1"/>
                                        <xs:element type="xs:string" name="email" minOccurs="1" maxOccurs="1"/>
                                        <xs:element type="xs:anyURI" name="website" minOccurs="0" maxOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="type">
                    <xs:annotation>
                        <xs:documentation>module type : classic, delivery, payment, ...</xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="classic"/>
                            <xs:enumeration value="delivery"/>
                            <xs:enumeration value="payment"/>
                            <xs:enumeration value="marketplace"/>
                            <xs:enumeration value="price"/>
                            <xs:enumeration value="accounting"/>
                            <xs:enumeration value="seo"/>
                            <xs:enumeration value="administration"/>
                            <xs:enumeration value="statistic"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="tags" minOccurs="0" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>Module tags</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="tag" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="required" minOccurs="0" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>Plugins that should be presents. Plugins are identified by their codes and an optional minimal version</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="module" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:string" name="version" use="optional"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="thelia" minOccurs="0" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>minimum required version of Thelia in 'dot' format (for example 1.2.3.4)</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="stability">
                    <xs:annotation>
                        <xs:documentation>current module stability: alpha, beta, rc, prod</xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="alpha"/>
                            <xs:enumeration value="beta"/>
                            <xs:enumeration value="rc"/>
                            <xs:enumeration value="prod"/>
                            <xs:enumeration value="other"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element type="xs:string" name="documentation" minOccurs="0" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>The name of the directory containing te documentation.</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element type="xs:anyURI" name="urlmiseajour" minOccurs="0" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>URL to test if a new version of the module exists. Will be called with two get parameters : module name, current version</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element type="xs:anyURI" name="updateurl" minOccurs="0" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>URL to test if a new version of the module exists. Will be called with two get parameters : module name, current version</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="mandatory" minOccurs="0" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>Flag for protected module</xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="0"/>
                            <xs:enumeration value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="hidden" minOccurs="0" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>Flag for visible module</xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="0"/>
                            <xs:enumeration value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="enabled-by-default" minOccurs="0" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>Whether the module is active right after the shop is installed. Defaults to 1. A module shipped with the distribution but declared 0 is registered inactive, even when a theme requires it: it stays listed in the back-office and waits for the merchant to activate it. The state a merchant chose is never rewritten by an update. A module listed under required by a module being activated is activated with it, whatever it declares here. Only this 2.2 format knows the element: a descriptor still on the 2.1 format (a single author element) has to move to authors before declaring it.</xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                        <xs:restriction base="xs:token">
                            <xs:enumeration value="0"/>
                            <xs:enumeration value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== thelia/thelia/local/modules/Front/Config/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="http://thelia.net/schema/dic/module"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://thelia.net/schema/dic/module http://thelia.net/schema/dic/module/module-2_2.xsd">
    <fullnamespace>Front\Front</fullnamespace>
    <descriptive locale="en_US">
        <title>Front integration</title>
        <description></description>
    </descriptive>
    <descriptive locale="fr_FR">
        <title>Front office module</title>
        <description></description>
    </descriptive>
    <languages>
        <language>en_US</language>
        <language>fr_FR</language>
    </languages>
    <version>2.6.1</version>
    <authors>
        <author>
            <name>Thelia team</name>
            <email>info@thelia.net</email>
        </author>
    </authors>
    <type>classic</type>
    <thelia>2.6.1</thelia>
    <stability>alpha</stability>
    <hidden>1</hidden>
</module>

=== thelia/thelia/local/modules/WebProfiler/Config/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="http://thelia.net/schema/dic/module"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://thelia.net/schema/dic/module http://thelia.net/schema/dic/module/module-2_2.xsd">
    <fullnamespace>WebProfiler\WebProfiler</fullnamespace>
    <descriptive locale="en_US">
        <title>Add thelia specific data to web profiler</title>
        <!--
        <subtitle></subtitle>
        <description></description>
        <postscriptum></postscriptum>
        -->
    </descriptive>
    <descriptive locale="fr_FR">
        <title>Ajoute des données spécifique a thelia dans le web profiler</title>
    </descriptive>
    <!-- <logo></logo> -->
    <!--<images-folder>images</images-folder>-->
    <languages>
        <language>en_US</language>
        <language>fr_FR</language>
    </languages>
    <version>2.6.1</version>
    <authors>
        <author>
            <name></name>
            <email></email>
        </author>
    </authors>
    <type>classic</type>
    <!--
    module dependencies
    <required>
        <module version="&gt;=0.1">Front</module>
        <module version="~1.0">HookCart</module>
        <module version="&gt;0.2">HookSearch</module>
    </required>
    -->
    <thelia>2.6.1</thelia>
    <stability>other</stability>
    <mandatory>0</mandatory>
    <hidden>1</hidden>
</module>

=== thelia/thelia/local/modules/TheliaTwig/Config/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="http://thelia.net/schema/dic/module"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://thelia.net/schema/dic/module http://thelia.net/schema/dic/module/module-2_2.xsd">
    <fullnamespace>TheliaTwig\TheliaTwig</fullnamespace>
    <descriptive locale="en_US">
        <title>Thelia Twig - template engine</title>
    </descriptive>
    <descriptive locale="fr_FR">
        <title>Thelia Twig - moteur de template</title>
    </descriptive>
    <languages>
        <language>en_US</language>
        <language>fr_FR</language>
    </languages>
    <version>0.0.1</version>
    <authors>
        <author>
            <name>Alexandre Nozi√®re - OpenStudio</name>
            <email>anoziere@openstudio.fr</email>
        </author>
    </authors>
    <type>classic</type>
    <thelia>2.5.0</thelia>
    <stability>other</stability>
    <mandatory>0</mandatory>
    <hidden>0</hidden>
</module>

=== thelia/thelia/local/modules/TheliaSmarty/Config/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="http://thelia.net/schema/dic/module"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://thelia.net/schema/dic/module http://thelia.net/schema/dic/module/module-2_2.xsd">
    <fullnamespace>TheliaSmarty\TheliaSmarty</fullnamespace>
    <descriptive locale="en_US">
        <title>Smarty template engine integration</title>
    </descriptive>
    <descriptive locale="fr_FR">
        <title>Intégration du moteur de template Smarty</title>
    </descriptive>
    <languages>
        <language>en_US</language>
        <language>fr_FR</language>
    </languages>
    <version>2.6.1</version>
    <authors>
        <author>
            <name>Manuel Raynaud</name>
            <email>manu@raynaud.io</email>
        </author>
    </authors>
    <type>classic</type>
    <thelia>2.6.1</thelia>
    <stability>alpha</stability>
    <mandatory>1</mandatory>
    <hidden>1</hidden>
</module>

=== thelia/thelia/local/modules/TheliaMigrateCountry/Config/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="http://thelia.net/schema/dic/module"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://thelia.net/schema/dic/module http://thelia.net/schema/dic/module/module-2_2.xsd">
    <fullnamespace>TheliaMigrateCountry\TheliaMigrateCountry</fullnamespace>
    <descriptive locale="en_US">
        <title>Countries/states migration tool</title>
    </descriptive>
    <descriptive locale="fr_FR">
        <title>Utilitaire de migration des pays/états</title>
    </descriptive>
    <languages>
        <language>en_US</language>
        <language>fr_FR</language>
    </languages>
    <version>2.6.1</version>
    <authors>
        <author>
            <name>Julien Chanséaume</name>
            <email>julien@thelia.net</email>
        </author>
    </authors>
    <type>classic</type>
    <thelia>2.6.1</thelia>
    <stability>alpha</stability>
</module>

=== thelia/thelia/local/modules/TwigEngine/Config/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="http://thelia.net/schema/dic/module"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://thelia.net/schema/dic/module http://thelia.net/schema/dic/module/module-2_2.xsd">
    <fullnamespace>TwigEngine\TwigEngine</fullnamespace>
    <descriptive locale="en_US">
        <title>Twig Engine - template engine</title>
    </descriptive>
    <descriptive locale="fr_FR">
        <title>Twig Engine - moteur de template</title>
    </descriptive>
    <languages>
        <language>en_US</language>
        <language>fr_FR</language>
    </languages>
    <version>1.0.0-alpha</version>
    <authors>
        <author>
            <name>Alexandre Nozi√®re - OpenStudio</name>
            <email>anoziere@openstudio.fr</email>
        </author>
    </authors>
    <type>classic</type>
    <thelia>2.5.0</thelia>
    <stability>other</stability>
    <mandatory>0</mandatory>
    <hidden>0</hidden>
</module>

=== thelia/thelia/local/modules/HookAdminHome/Config/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="http://thelia.net/schema/dic/module"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://thelia.net/schema/dic/module http://thelia.net/schema/dic/module/module-2_2.xsd">
    <fullnamespace>HookAdminHome\HookAdminHome</fullnamespace>
    <descriptive locale="en_US">
        <title>Displays the default blocks on the homepage of the administration</title>
    </descriptive>
    <descriptive locale="fr_FR">
        <title>Affiche les blocs par défaut sur la page d'accueil de l'administration</title>
    </descriptive>
    <languages>
        <language>en_US</language>
        <language>fr_FR</language>
    </languages>
    <version>2.6.1</version>
    <authors>
        <author>
            <name>Gilles Bourgeat</name>
            <email>gilles@thelia.net</email>
        </author>
        <author>
            <name>Franck Allimant</name>
            <company>CQFDev</company>
            <email>franck@cqfdev.fr</email>
            <website>www.cqfdev.fr</website>
        </author>
    </authors>
    <type>classic</type>
    <thelia>2.6.1</thelia>
    <stability>prod</stability>
</module>

=== thelia/thelia/core/lib/Thelia/Command/Skeleton/Module/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="http://thelia.net/schema/dic/module"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://thelia.net/schema/dic/module http://thelia.net/schema/dic/module/module-2_2.xsd">
    <fullnamespace>%%NAMESPACE%%\%%CLASSNAME%%</fullnamespace>
    <descriptive locale="en_US">
        <title>Automatically generated module - please update module.xml file</title>
        <!--
        <subtitle></subtitle>
        <description></description>
        <postscriptum></postscriptum>
        -->
    </descriptive>
    <descriptive locale="fr_FR">
        <title>Module généré automatiquement - éditez le fichier module.xml</title>
    </descriptive>
    <!-- <logo></logo> -->
    <!--<images-folder>images</images-folder>-->
    <languages>
        <language>en_US</language>
        <language>fr_FR</language>
    </languages>
    <version></version>
    <authors>
        <author>
            <name></name>
            <email></email>
        </author>
    </authors>
    <type>classic</type>
    <!--
    module dependencies
    <required>
        <module version="&gt;=0.1">Front</module>
        <module version="~1.0">HookCart</module>
        <module version="&gt;0.2">HookSearch</module>
    </required>
    -->
    <thelia>3.0.0</thelia>
    <stability>other</stability>
    <mandatory>0</mandatory>
    <hidden>0</hidden>
</module>
