=== thelia/thelia/core/lib/Thelia/Core/DependencyInjection/Loader/schema/dic/config/thelia-1.0.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns="http://thelia.net/schema/dic/config"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://thelia.net/schema/dic/config"
            elementFormDefault="qualified">

    <xsd:element name="config" type="config" />

    <xsd:complexType name="config">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="loops" type="loops" />
            <xsd:element name="filters" type="filters" />
            <xsd:element name="templateDirectives" type="templateDirectives" />
            <xsd:element name="services" type="services" />
            <xsd:element name="parameters" type="parameters"/>
            <xsd:element name="commands" type="commands"/>
            <xsd:element name="forms" type="forms" />
            <xsd:element name="routing" type="routing" />
            <xsd:element name="hooks" type="hooks" />
            <xsd:element name="export_categories" type="export_categories" />
            <xsd:element name="exports" type="exports" />
            <xsd:element name="import_categories" type="import_categories" />
            <xsd:element name="imports" type="imports" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="parameters">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="parameter" type="parameter" />
        </xsd:choice>
        <xsd:attribute name="type" type="parameter_type" />
        <xsd:attribute name="key" type="xsd:string" />
    </xsd:complexType>

    <xsd:complexType name="parameter" mixed="true">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="parameter" type="parameter" />
        </xsd:choice>
        <xsd:attribute name="type" type="parameter_type" />
        <xsd:attribute name="id" type="xsd:string" />
        <xsd:attribute name="key" type="xsd:string" />
        <xsd:attribute name="on-invalid" type="invalid_sequence" />
    </xsd:complexType>

    <xsd:simpleType name="parameter_type">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="collection" />
            <xsd:enumeration value="service" />
            <xsd:enumeration value="string" />
            <xsd:enumeration value="constant" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="invalid_sequence">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="null" />
            <xsd:enumeration value="ignore" />
            <xsd:enumeration value="exception" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="routing">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="file" type="file"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="file">
        <xsd:attribute name="path" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="loops">
        <xsd:choice minOccurs="0" maxOccurs="unbounded" >
            <xsd:element name="loop" type="loop"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="loop">
        <xsd:attribute name="class" type="xsd:string" use="required" />
        <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="commands">
        <xsd:choice minOccurs="0" maxOccurs="unbounded" >
            <xsd:element name="command" type="command"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="command">
        <xsd:attribute name="class" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="forms">
        <xsd:choice minOccurs="0" maxOccurs="unbounded" >
            <xsd:element name="form" type="form" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="form">
        <xsd:attribute name="name" type="xsd:string" use="required" />
        <xsd:attribute name="class" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="filters">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="filter" type="filter" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="filter">
        <xsd:attribute name="class" type="xsd:string" use="required" />
        <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="templateDirectives">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="templateDirective" type="templateDirective" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="templateDirective">
        <xsd:attribute name="class" type="xsd:string" use="required" />
        <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="services">
        <xsd:annotation>
            <xsd:documentation><![CDATA[
        Enclosing element for the definition of all services
      ]]></xsd:documentation>
        </xsd:annotation>
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="service" type="service" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="hooks">
        <xsd:annotation>
            <xsd:documentation><![CDATA[
        Enclosing element for the definition of all hooks
      ]]></xsd:documentation>
        </xsd:annotation>
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="hook" type="hook" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="service">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="file" type="xsd:string" minOccurs="0" maxOccurs="1" />
            <xsd:element name="argument" type="argument" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="factory" type="factory" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="configurator" type="configurator" minOccurs="0" maxOccurs="1" />
            <xsd:element name="call" type="call" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="tag" type="tag" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="property" type="property" minOccurs="0" maxOccurs="unbounded" />
        </xsd:choice>
        <xsd:attribute name="id" type="xsd:string" />
        <xsd:attribute name="class" type="xsd:string" />
        <xsd:attribute name="scope" type="xsd:string" />
        <xsd:attribute name="public" type="boolean" />
        <xsd:attribute name="synthetic" type="boolean" />
        <xsd:attribute name="abstract" type="boolean" />
        <xsd:attribute name="factory" type="xsd:string" />
        <xsd:attribute name="alias" type="xsd:string" />
        <xsd:attribute name="parent" type="xsd:string" />
        <xsd:attribute name="shared" type="xsd:boolean" />
        <xsd:attribute name="decorates" type="xsd:string" />
        <xsd:attribute name="decoration-on-invalid" type="invalid_decorated_service_sequence" />
        <xsd:attribute name="decoration-inner-name" type="xsd:string" />
        <xsd:attribute name="decoration-priority" type="xsd:integer" />
    </xsd:complexType>

    <xsd:simpleType name="invalid_decorated_service_sequence">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="null" />
            <xsd:enumeration value="ignore" />
            <xsd:enumeration value="exception" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="hook">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="file" type="xsd:string" minOccurs="0" maxOccurs="1" />
            <xsd:element name="argument" type="argument" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="configurator" type="configurator" minOccurs="0" maxOccurs="1" />
            <xsd:element name="call" type="call" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="tag" type="hook_tag" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="property" type="property" minOccurs="0" maxOccurs="unbounded" />
        </xsd:choice>
        <xsd:attribute name="id" type="xsd:string" />
        <xsd:attribute name="class" type="xsd:string" />
        <xsd:attribute name="scope" type="xsd:string" />
        <xsd:attribute name="public" type="boolean" />
        <xsd:attribute name="synthetic" type="boolean" />
        <xsd:attribute name="abstract" type="boolean" />
        <xsd:attribute name="factory" type="xsd:string" />
        <xsd:attribute name="alias" type="xsd:string" />
        <xsd:attribute name="parent" type="xsd:string" />
        <xsd:attribute name="event" type="xsd:string" />
        <xsd:attribute name="type" type="hook_type" />
        <xsd:attribute name="active" type="hook_active" />
    </xsd:complexType>

    <xsd:complexType name="hook_tag">
        <xsd:attribute name="name" type="xsd:string" />
        <xsd:attribute name="event" type="xsd:string" />
        <xsd:attribute name="method" type="xsd:string" />
        <xsd:attribute name="type" type="hook_type" />
        <xsd:attribute name="active" type="hook_active" />
        <xsd:attribute name="templates" type="xsd:string" />
        <xsd:attribute name="position" type="hook_position" />
    </xsd:complexType>

    <xsd:simpleType name="hook_position">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="1" />
            <xsd:maxInclusive value="999" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="hook_type">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="fo" />
            <xsd:enumeration value="front" />
            <xsd:enumeration value="frontoffice" />
            <xsd:enumeration value="bo" />
            <xsd:enumeration value="back" />
            <xsd:enumeration value="backoffice" />
            <xsd:enumeration value="pdf" />
            <xsd:enumeration value="email" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="hook_active">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="0" />
            <xsd:enumeration value="1" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="tag">
        <xsd:attribute name="name" type="xsd:string" />
        <xsd:anyAttribute namespace="##any" processContents="lax" />
    </xsd:complexType>

    <xsd:complexType name="property" mixed="true">
        <xsd:choice minOccurs="0" maxOccurs="1">
            <xsd:element name="service" type="service" />
        </xsd:choice>
        <xsd:attribute name="type" type="argument_type" />
        <xsd:attribute name="id" type="xsd:string" />
        <xsd:attribute name="name" type="xsd:string" />
        <xsd:attribute name="on-invalid" type="xsd:string" />
        <xsd:attribute name="strict" type="boolean" />
    </xsd:complexType>

    <xsd:complexType name="argument" mixed="true">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="argument" type="argument" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="service" type="service" />
        </xsd:choice>
        <xsd:attribute name="type" type="argument_type" />
        <xsd:attribute name="id" type="xsd:string" />
        <xsd:attribute name="key" type="xsd:string" />
        <xsd:attribute name="index" type="xsd:integer" />
        <xsd:attribute name="on-invalid" type="xsd:string" />
        <xsd:attribute name="strict" type="boolean" />
    </xsd:complexType>

    <xsd:complexType name="factory" mixed="true">
        <xsd:attribute name="service" type="xsd:string" />
        <xsd:attribute name="class" type="xsd:string" />
        <xsd:attribute name="method" type="xsd:string" />
    </xsd:complexType>

    <xsd:complexType name="call" mixed="true">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="argument" type="argument" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="service" type="service" />
        </xsd:choice>
        <xsd:attribute name="method" type="xsd:string" />
    </xsd:complexType>

    <xsd:simpleType name="argument_type">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="collection" />
            <xsd:enumeration value="service" />
            <xsd:enumeration value="string" />
            <xsd:enumeration value="constant" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="boolean">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="(%.+%|true|false)" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="configurator">
        <xsd:attribute name="id" type="xsd:string" />
        <xsd:attribute name="service" type="xsd:string" />
        <xsd:attribute name="class" type="xsd:string" />
        <xsd:attribute name="method" type="xsd:string" />
        <xsd:attribute name="function" type="xsd:string" />
    </xsd:complexType>

    <xsd:complexType name="export_categories">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="export_category" type="export_category"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="export_category">
        <xsd:choice maxOccurs="unbounded" minOccurs="1">
            <xsd:element name="title" type="export_category_title" />
        </xsd:choice>

        <xsd:attribute name="id" use="required" type="xsd:string" />
    </xsd:complexType>

    <xsd:complexType name="export_category_title">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="locale" type="xsd:string" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="exports">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="export" type="export"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="export">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="export_descriptive" type="export_descriptive" />
        </xsd:choice>

        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="class" type="xsd:string" use="required"/>
        <xsd:attribute name="category_id" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="export_descriptive">
        <xsd:sequence minOccurs="1" maxOccurs="1">
            <xsd:element name="title" type="xsd:string" />
            <xsd:element minOccurs="0" maxOccurs="1" name="description" type="xsd:string" />
        </xsd:sequence>

        <xsd:attribute name="locale" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="import_categories">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="import_category" type="import_category"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="import_category">
        <xsd:choice maxOccurs="unbounded" minOccurs="1">
            <xsd:element name="title" type="import_category_title" />
        </xsd:choice>

        <xsd:attribute name="id" use="required" type="xsd:string" />
    </xsd:complexType>

    <xsd:complexType name="import_category_title">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="locale" type="xsd:string" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="imports">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="import" type="import"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="import">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="import_descriptive" type="import_descriptive" />
        </xsd:choice>

        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="class" type="xsd:string" use="required"/>
        <xsd:attribute name="category_id" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="import_descriptive">
        <xsd:sequence minOccurs="1" maxOccurs="1">
            <xsd:element name="title" type="xsd:string" />
            <xsd:element minOccurs="0" maxOccurs="1" name="description" type="xsd:string" />
        </xsd:sequence>

        <xsd:attribute name="locale" type="xsd:string" use="required" />
    </xsd:complexType>

</xsd:schema>

=== thelia/thelia/core/lib/Thelia/Config/Resources/export.xml
<?xml version="1.0" encoding="UTF-8" ?>

<config xmlns="http://thelia.net/schema/dic/config"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://thelia.net/schema/dic/config http://thelia.net/schema/dic/config/thelia-1.0.xsd">

    <export_categories>
        <export_category id="thelia.export.customer">
            <title locale="en_US">Customers</title>
            <title locale="fr_FR">Clients</title>
        </export_category>
        <export_category id="thelia.export.products">
            <title locale="en_US">Products</title>
            <title locale="fr_FR">Produits</title>
        </export_category>
        <export_category id="thelia.export.content">
            <title locale="en_US">Content</title>
            <title locale="fr_FR">Contenu</title>
        </export_category>
        <export_category id="thelia.export.orders">
            <title locale="en_US">Orders</title>
            <title locale="fr_FR">Commandes</title>
        </export_category>
        <export_category id="thelia.export.modules">
            <title locale="en_US">Modules</title>
            <title locale="fr_FR">Modules</title>
        </export_category>
        <export_category id="thelia.export.reports">
            <title locale="en_US">Reports</title>
            <title locale="fr_FR">Rapports</title>
        </export_category>
    </export_categories>

    <exports>
        <export id="thelia.export.mailing" category_id="thelia.export.customer" class="Thelia\Domain\DataTransfer\Export\Type\MailingExport">
            <export_descriptive locale="fr_FR">
                <title>Mailing</title>
                <description>Exporter le nom, prénom et adresse mail des abonnés à la newsletter</description>
            </export_descriptive>
            <export_descriptive locale="en_US">
                <title>Mailing</title>
                <description>Export the last name, first name and email address of the newsletter subscribers</description>
            </export_descriptive>
        </export>

        <export id="thelia.export.complete" category_id="thelia.export.customer" class="Thelia\Domain\DataTransfer\Export\Type\CustomerExport">
            <export_descriptive locale="fr_FR">
                <title>Clients</title>
                <description>Exporter toutes les informations à propos de vos clients</description>
            </export_descriptive>
            <export_descriptive locale="en_US">
                <title>Customers</title>
                <description>Export all the information about your customers</description>
            </export_descriptive>
        </export>

        <export id="thelia.export.prices" class="Thelia\Domain\DataTransfer\Export\Type\ProductPricesExport" category_id="thelia.export.products">
            <export_descriptive locale="fr_FR">
                <title>Prix des produits Hors-Taxes</title>
                <description>Exporter le prix hors taxes de vos produits</description>
            </export_descriptive>
            <export_descriptive locale="en_US">
                <title>Product prices excluding taxes</title>
                <description>Export the prices of the products excluding taxes</description>
            </export_descriptive>
        </export>

        <export id="thelia.export.taxed_prices" class="Thelia\Domain\DataTransfer\Export\Type\ProductTaxedPricesExport" category_id="thelia.export.products">
            <export_descriptive locale="fr_FR">
                <title>Prix des produits TTC</title>
                <description>Exporter le prix TTC de vos produits</description>
            </export_descriptive>
            <export_descriptive locale="en_US">
                <title>Product prices including taxes</title>
                <description>Export the prices of the products including taxes</description>
            </export_descriptive>
        </export>

        <export id="thelia.export.product_seo" class="Thelia\Domain\DataTransfer\Export\Type\ProductSEOExport" category_id="thelia.export.products">
            <export_descriptive locale="en_US">
                <title>Product SEO information</title>
                <description>
                    Export the SEO information ( rewritten url, meta description and keywords, page title ) of your products
                </description>
            </export_descriptive>
            <export_descriptive locale="fr_FR">
                <title>Informations SEO des produits</title>
                <description>
                    Exporter les informations SEO de vos produits
                    ( url réécrites, meta description et mots clés, titre ) de vos produits
                </description>
            </export_descriptive>
        </export>

        <export id="thelia.export.content" class="Thelia\Domain\DataTransfer\Export\Type\ContentExport" category_id="thelia.export.content">
            <export_descriptive locale="en_US">
                <title>Contents and folder</title>
                <description>
                    Export your contents and their related folders
                </description>
            </export_descriptive>
            <export_descriptive locale="fr_FR">
                <title>Contenus et dossiers</title>
                <description>
                    Exporter vos contenus et les dossiers associés
                </description>
            </export_descriptive>
        </export>

        <export id="thelia.export.orders" class="Thelia\Domain\DataTransfer\Export\Type\OrderExport" category_id="thelia.export.orders">
            <export_descriptive locale="en_US">
                <title>Full orders</title>
                <description>
                    Export your orders
                </description>
            </export_descriptive>
            <export_descriptive locale="fr_FR">
                <title>Commandes complètes</title>
                <description>
                    Exporter vos commandes
                </description>
            </export_descriptive>
        </export>

        <export id="thelia.export.order_lines" class="Thelia\Domain\DataTransfer\Export\Type\OrderLineExport" category_id="thelia.export.orders">
            <export_descriptive locale="en_US">
                <title>Order lines</title>
                <description>
                    One row per order line: product and combination references, GTIN and manufacturer part number as they were when the order was placed, quantity and unit price.
                </description>
            </export_descriptive>
            <export_descriptive locale="fr_FR">
                <title>Lignes de commande</title>
                <description>
                    Une ligne par article commandé : références du produit et de la déclinaison, GTIN et référence fabricant tels qu'au moment de la commande, quantité et prix unitaire.
                </description>
            </export_descriptive>
        </export>

        <export id="thelia.export.product_i18n" class="Thelia\Domain\DataTransfer\Export\Type\ProductI18nExport" category_id="thelia.export.products">
            <export_descriptive locale="en_US">
                <title>Product I18n information</title>
                <description>
                    Export the I18n information (title, chapo, description, postscriptum) of your products
                </description>
            </export_descriptive>
            <export_descriptive locale="fr_FR">
                <title>Informations I18n des produits</title>
                <description>
                    Exporter les informations I18n de vos produits (titre produit, résumé, description, conclusion)
                </description>
            </export_descriptive>
        </export>

        <export id="thelia.export.conversion_funnel" class="Thelia\Domain\DataTransfer\Export\Type\ConversionFunnelExport" category_id="thelia.export.reports">
            <export_descriptive locale="en_US">
                <title>Conversion funnel</title>
                <description>
                    Carts created, carts with a line, carts with a delivery module, carts with a payment module, orders placed and orders paid, one row per day. Without a period, from the earliest date still covered by the cart retention window until today.
                </description>
            </export_descriptive>
            <export_descriptive locale="fr_FR">
                <title>Entonnoir de conversion</title>
                <description>
                    Paniers créés, paniers avec article, paniers avec mode de livraison, paniers avec moyen de paiement, commandes passées et payées, une ligne par jour. Sans période, depuis la date la plus ancienne encore couverte par la durée de conservation des paniers jusqu'à aujourd'hui.
                </description>
            </export_descriptive>
        </export>
    </exports>
</config>
